// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TgMatchInfo.proto

package com.example.mvvm_navigation.protobuf;

public final class SocketTgMatchInfo {
  private SocketTgMatchInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface TgMatchUpdateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:socketProtos.TgMatchInfo.TgMatchUpdate)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.socketProtos.command.Command command = 1;</code>
     */
    int getCommandValue();
    /**
     * <code>.socketProtos.command.Command command = 1;</code>
     */
    Socket.Command getCommand();

    /**
     * <code>repeated .socketProtos.TgMatchInfo.TgMatchInfo data = 2;</code>
     */
    java.util.List<TgMatchInfo>
        getDataList();
    /**
     * <code>repeated .socketProtos.TgMatchInfo.TgMatchInfo data = 2;</code>
     */
    TgMatchInfo getData(int index);
    /**
     * <code>repeated .socketProtos.TgMatchInfo.TgMatchInfo data = 2;</code>
     */
    int getDataCount();
  }
  /**
   * Protobuf type {@code socketProtos.TgMatchInfo.TgMatchUpdate}
   */
  public  static final class TgMatchUpdate extends
      com.google.protobuf.GeneratedMessageLite<
          TgMatchUpdate, TgMatchUpdate.Builder> implements
      // @@protoc_insertion_point(message_implements:socketProtos.TgMatchInfo.TgMatchUpdate)
      TgMatchUpdateOrBuilder {
    private TgMatchUpdate() {
      data_ = emptyProtobufList();
    }
    public static final int COMMAND_FIELD_NUMBER = 1;
    private int command_;
    /**
     * <code>.socketProtos.command.Command command = 1;</code>
     */
    @Override
    public int getCommandValue() {
      return command_;
    }
    /**
     * <code>.socketProtos.command.Command command = 1;</code>
     */
    @Override
    public Socket.Command getCommand() {
      Socket.Command result = Socket.Command.forNumber(command_);
      return result == null ? Socket.Command.UNRECOGNIZED : result;
    }
    /**
     * <code>.socketProtos.command.Command command = 1;</code>
     */
    private void setCommandValue(int value) {
        command_ = value;
    }
    /**
     * <code>.socketProtos.command.Command command = 1;</code>
     */
    private void setCommand(Socket.Command value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      command_ = value.getNumber();
    }
    /**
     * <code>.socketProtos.command.Command command = 1;</code>
     */
    private void clearCommand() {
      
      command_ = 0;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<TgMatchInfo> data_;
    /**
     * <code>repeated .socketProtos.TgMatchInfo.TgMatchInfo data = 2;</code>
     */
    @Override
    public java.util.List<TgMatchInfo> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .socketProtos.TgMatchInfo.TgMatchInfo data = 2;</code>
     */
    public java.util.List<? extends TgMatchInfoOrBuilder>
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .socketProtos.TgMatchInfo.TgMatchInfo data = 2;</code>
     */
    @Override
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .socketProtos.TgMatchInfo.TgMatchInfo data = 2;</code>
     */
    @Override
    public TgMatchInfo getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .socketProtos.TgMatchInfo.TgMatchInfo data = 2;</code>
     */
    public TgMatchInfoOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }
    private void ensureDataIsMutable() {
      if (!data_.isModifiable()) {
        data_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(data_);
       }
    }

    /**
     * <code>repeated .socketProtos.TgMatchInfo.TgMatchInfo data = 2;</code>
     */
    private void setData(
        int index, TgMatchInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureDataIsMutable();
      data_.set(index, value);
    }
    /**
     * <code>repeated .socketProtos.TgMatchInfo.TgMatchInfo data = 2;</code>
     */
    private void setData(
        int index, TgMatchInfo.Builder builderForValue) {
      ensureDataIsMutable();
      data_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .socketProtos.TgMatchInfo.TgMatchInfo data = 2;</code>
     */
    private void addData(TgMatchInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureDataIsMutable();
      data_.add(value);
    }
    /**
     * <code>repeated .socketProtos.TgMatchInfo.TgMatchInfo data = 2;</code>
     */
    private void addData(
        int index, TgMatchInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureDataIsMutable();
      data_.add(index, value);
    }
    /**
     * <code>repeated .socketProtos.TgMatchInfo.TgMatchInfo data = 2;</code>
     */
    private void addData(
        TgMatchInfo.Builder builderForValue) {
      ensureDataIsMutable();
      data_.add(builderForValue.build());
    }
    /**
     * <code>repeated .socketProtos.TgMatchInfo.TgMatchInfo data = 2;</code>
     */
    private void addData(
        int index, TgMatchInfo.Builder builderForValue) {
      ensureDataIsMutable();
      data_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .socketProtos.TgMatchInfo.TgMatchInfo data = 2;</code>
     */
    private void addAllData(
        Iterable<? extends TgMatchInfo> values) {
      ensureDataIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, data_);
    }
    /**
     * <code>repeated .socketProtos.TgMatchInfo.TgMatchInfo data = 2;</code>
     */
    private void clearData() {
      data_ = emptyProtobufList();
    }
    /**
     * <code>repeated .socketProtos.TgMatchInfo.TgMatchInfo data = 2;</code>
     */
    private void removeData(int index) {
      ensureDataIsMutable();
      data_.remove(index);
    }

    public static TgMatchUpdate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static TgMatchUpdate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static TgMatchUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static TgMatchUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static TgMatchUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static TgMatchUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static TgMatchUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static TgMatchUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static TgMatchUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static TgMatchUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static TgMatchUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static TgMatchUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(TgMatchUpdate prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code socketProtos.TgMatchInfo.TgMatchUpdate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          TgMatchUpdate, Builder> implements
        // @@protoc_insertion_point(builder_implements:socketProtos.TgMatchInfo.TgMatchUpdate)
        TgMatchUpdateOrBuilder {
      // Construct using com.example.mvvm_navigation.protobuf.SocketTgMatchInfo.TgMatchUpdate.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.socketProtos.command.Command command = 1;</code>
       */
      @Override
      public int getCommandValue() {
        return instance.getCommandValue();
      }
      /**
       * <code>.socketProtos.command.Command command = 1;</code>
       */
      public Builder setCommandValue(int value) {
        copyOnWrite();
        instance.setCommandValue(value);
        return this;
      }
      /**
       * <code>.socketProtos.command.Command command = 1;</code>
       */
      @Override
      public Socket.Command getCommand() {
        return instance.getCommand();
      }
      /**
       * <code>.socketProtos.command.Command command = 1;</code>
       */
      public Builder setCommand(Socket.Command value) {
        copyOnWrite();
        instance.setCommand(value);
        return this;
      }
      /**
       * <code>.socketProtos.command.Command command = 1;</code>
       */
      public Builder clearCommand() {
        copyOnWrite();
        instance.clearCommand();
        return this;
      }

      /**
       * <code>repeated .socketProtos.TgMatchInfo.TgMatchInfo data = 2;</code>
       */
      @Override
      public java.util.List<TgMatchInfo> getDataList() {
        return java.util.Collections.unmodifiableList(
            instance.getDataList());
      }
      /**
       * <code>repeated .socketProtos.TgMatchInfo.TgMatchInfo data = 2;</code>
       */
      @Override
      public int getDataCount() {
        return instance.getDataCount();
      }/**
       * <code>repeated .socketProtos.TgMatchInfo.TgMatchInfo data = 2;</code>
       */
      @Override
      public TgMatchInfo getData(int index) {
        return instance.getData(index);
      }
      /**
       * <code>repeated .socketProtos.TgMatchInfo.TgMatchInfo data = 2;</code>
       */
      public Builder setData(
          int index, TgMatchInfo value) {
        copyOnWrite();
        instance.setData(index, value);
        return this;
      }
      /**
       * <code>repeated .socketProtos.TgMatchInfo.TgMatchInfo data = 2;</code>
       */
      public Builder setData(
          int index, TgMatchInfo.Builder builderForValue) {
        copyOnWrite();
        instance.setData(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .socketProtos.TgMatchInfo.TgMatchInfo data = 2;</code>
       */
      public Builder addData(TgMatchInfo value) {
        copyOnWrite();
        instance.addData(value);
        return this;
      }
      /**
       * <code>repeated .socketProtos.TgMatchInfo.TgMatchInfo data = 2;</code>
       */
      public Builder addData(
          int index, TgMatchInfo value) {
        copyOnWrite();
        instance.addData(index, value);
        return this;
      }
      /**
       * <code>repeated .socketProtos.TgMatchInfo.TgMatchInfo data = 2;</code>
       */
      public Builder addData(
          TgMatchInfo.Builder builderForValue) {
        copyOnWrite();
        instance.addData(builderForValue);
        return this;
      }
      /**
       * <code>repeated .socketProtos.TgMatchInfo.TgMatchInfo data = 2;</code>
       */
      public Builder addData(
          int index, TgMatchInfo.Builder builderForValue) {
        copyOnWrite();
        instance.addData(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .socketProtos.TgMatchInfo.TgMatchInfo data = 2;</code>
       */
      public Builder addAllData(
          Iterable<? extends TgMatchInfo> values) {
        copyOnWrite();
        instance.addAllData(values);
        return this;
      }
      /**
       * <code>repeated .socketProtos.TgMatchInfo.TgMatchInfo data = 2;</code>
       */
      public Builder clearData() {
        copyOnWrite();
        instance.clearData();
        return this;
      }
      /**
       * <code>repeated .socketProtos.TgMatchInfo.TgMatchInfo data = 2;</code>
       */
      public Builder removeData(int index) {
        copyOnWrite();
        instance.removeData(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:socketProtos.TgMatchInfo.TgMatchUpdate)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new TgMatchUpdate();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "command_",
              "data_",
              TgMatchInfo.class,
            };
            String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\f\u0002\u001b" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<TgMatchUpdate> parser = PARSER;
          if (parser == null) {
            synchronized (TgMatchUpdate.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:socketProtos.TgMatchInfo.TgMatchUpdate)
    private static final TgMatchUpdate DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new TgMatchUpdate();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        TgMatchUpdate.class, DEFAULT_INSTANCE);
    }
    public static TgMatchUpdate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<TgMatchUpdate> PARSER;

    public static com.google.protobuf.Parser<TgMatchUpdate> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface TgMatchInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:socketProtos.TgMatchInfo.TgMatchInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * 賽事id
     * </pre>
     *
     * <code>int32 matchId = 1;</code>
     */
    int getMatchId();

    /**
     * <pre>
     * TG賽事是否開啟 0未開啟 1開啟
     * </pre>
     *
     * <code>int32 tgStatus = 2;</code>
     */
    int getTgStatus();

    /**
     * <pre>
     * 開賽時間(timestamp)
     * </pre>
     *
     * <code>int32 openDate = 3;</code>
     */
    int getOpenDate();

    /**
     * <pre>
     * 總下注量
     * </pre>
     *
     * <code>int32 betsCount = 4;</code>
     */
    int getBetsCount();

    /**
     * <code>repeated .socketProtos.TgMatchInfo.BetDetail betDetail = 5;</code>
     */
    java.util.List<BetDetail>
        getBetDetailList();
    /**
     * <code>repeated .socketProtos.TgMatchInfo.BetDetail betDetail = 5;</code>
     */
    BetDetail getBetDetail(int index);
    /**
     * <code>repeated .socketProtos.TgMatchInfo.BetDetail betDetail = 5;</code>
     */
    int getBetDetailCount();
  }
  /**
   * Protobuf type {@code socketProtos.TgMatchInfo.TgMatchInfo}
   */
  public  static final class TgMatchInfo extends
      com.google.protobuf.GeneratedMessageLite<
          TgMatchInfo, TgMatchInfo.Builder> implements
      // @@protoc_insertion_point(message_implements:socketProtos.TgMatchInfo.TgMatchInfo)
      TgMatchInfoOrBuilder {
    private TgMatchInfo() {
      betDetail_ = emptyProtobufList();
    }
    public static final int MATCHID_FIELD_NUMBER = 1;
    private int matchId_;
    /**
     * <pre>
     * 賽事id
     * </pre>
     *
     * <code>int32 matchId = 1;</code>
     */
    @Override
    public int getMatchId() {
      return matchId_;
    }
    /**
     * <pre>
     * 賽事id
     * </pre>
     *
     * <code>int32 matchId = 1;</code>
     */
    private void setMatchId(int value) {
      
      matchId_ = value;
    }
    /**
     * <pre>
     * 賽事id
     * </pre>
     *
     * <code>int32 matchId = 1;</code>
     */
    private void clearMatchId() {
      
      matchId_ = 0;
    }

    public static final int TGSTATUS_FIELD_NUMBER = 2;
    private int tgStatus_;
    /**
     * <pre>
     * TG賽事是否開啟 0未開啟 1開啟
     * </pre>
     *
     * <code>int32 tgStatus = 2;</code>
     */
    @Override
    public int getTgStatus() {
      return tgStatus_;
    }
    /**
     * <pre>
     * TG賽事是否開啟 0未開啟 1開啟
     * </pre>
     *
     * <code>int32 tgStatus = 2;</code>
     */
    private void setTgStatus(int value) {
      
      tgStatus_ = value;
    }
    /**
     * <pre>
     * TG賽事是否開啟 0未開啟 1開啟
     * </pre>
     *
     * <code>int32 tgStatus = 2;</code>
     */
    private void clearTgStatus() {
      
      tgStatus_ = 0;
    }

    public static final int OPENDATE_FIELD_NUMBER = 3;
    private int openDate_;
    /**
     * <pre>
     * 開賽時間(timestamp)
     * </pre>
     *
     * <code>int32 openDate = 3;</code>
     */
    @Override
    public int getOpenDate() {
      return openDate_;
    }
    /**
     * <pre>
     * 開賽時間(timestamp)
     * </pre>
     *
     * <code>int32 openDate = 3;</code>
     */
    private void setOpenDate(int value) {
      
      openDate_ = value;
    }
    /**
     * <pre>
     * 開賽時間(timestamp)
     * </pre>
     *
     * <code>int32 openDate = 3;</code>
     */
    private void clearOpenDate() {
      
      openDate_ = 0;
    }

    public static final int BETSCOUNT_FIELD_NUMBER = 4;
    private int betsCount_;
    /**
     * <pre>
     * 總下注量
     * </pre>
     *
     * <code>int32 betsCount = 4;</code>
     */
    @Override
    public int getBetsCount() {
      return betsCount_;
    }
    /**
     * <pre>
     * 總下注量
     * </pre>
     *
     * <code>int32 betsCount = 4;</code>
     */
    private void setBetsCount(int value) {
      
      betsCount_ = value;
    }
    /**
     * <pre>
     * 總下注量
     * </pre>
     *
     * <code>int32 betsCount = 4;</code>
     */
    private void clearBetsCount() {
      
      betsCount_ = 0;
    }

    public static final int BETDETAIL_FIELD_NUMBER = 5;
    private com.google.protobuf.Internal.ProtobufList<BetDetail> betDetail_;
    /**
     * <code>repeated .socketProtos.TgMatchInfo.BetDetail betDetail = 5;</code>
     */
    @Override
    public java.util.List<BetDetail> getBetDetailList() {
      return betDetail_;
    }
    /**
     * <code>repeated .socketProtos.TgMatchInfo.BetDetail betDetail = 5;</code>
     */
    public java.util.List<? extends BetDetailOrBuilder>
        getBetDetailOrBuilderList() {
      return betDetail_;
    }
    /**
     * <code>repeated .socketProtos.TgMatchInfo.BetDetail betDetail = 5;</code>
     */
    @Override
    public int getBetDetailCount() {
      return betDetail_.size();
    }
    /**
     * <code>repeated .socketProtos.TgMatchInfo.BetDetail betDetail = 5;</code>
     */
    @Override
    public BetDetail getBetDetail(int index) {
      return betDetail_.get(index);
    }
    /**
     * <code>repeated .socketProtos.TgMatchInfo.BetDetail betDetail = 5;</code>
     */
    public BetDetailOrBuilder getBetDetailOrBuilder(
        int index) {
      return betDetail_.get(index);
    }
    private void ensureBetDetailIsMutable() {
      if (!betDetail_.isModifiable()) {
        betDetail_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(betDetail_);
       }
    }

    /**
     * <code>repeated .socketProtos.TgMatchInfo.BetDetail betDetail = 5;</code>
     */
    private void setBetDetail(
        int index, BetDetail value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureBetDetailIsMutable();
      betDetail_.set(index, value);
    }
    /**
     * <code>repeated .socketProtos.TgMatchInfo.BetDetail betDetail = 5;</code>
     */
    private void setBetDetail(
        int index, BetDetail.Builder builderForValue) {
      ensureBetDetailIsMutable();
      betDetail_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .socketProtos.TgMatchInfo.BetDetail betDetail = 5;</code>
     */
    private void addBetDetail(BetDetail value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureBetDetailIsMutable();
      betDetail_.add(value);
    }
    /**
     * <code>repeated .socketProtos.TgMatchInfo.BetDetail betDetail = 5;</code>
     */
    private void addBetDetail(
        int index, BetDetail value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureBetDetailIsMutable();
      betDetail_.add(index, value);
    }
    /**
     * <code>repeated .socketProtos.TgMatchInfo.BetDetail betDetail = 5;</code>
     */
    private void addBetDetail(
        BetDetail.Builder builderForValue) {
      ensureBetDetailIsMutable();
      betDetail_.add(builderForValue.build());
    }
    /**
     * <code>repeated .socketProtos.TgMatchInfo.BetDetail betDetail = 5;</code>
     */
    private void addBetDetail(
        int index, BetDetail.Builder builderForValue) {
      ensureBetDetailIsMutable();
      betDetail_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .socketProtos.TgMatchInfo.BetDetail betDetail = 5;</code>
     */
    private void addAllBetDetail(
        Iterable<? extends BetDetail> values) {
      ensureBetDetailIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, betDetail_);
    }
    /**
     * <code>repeated .socketProtos.TgMatchInfo.BetDetail betDetail = 5;</code>
     */
    private void clearBetDetail() {
      betDetail_ = emptyProtobufList();
    }
    /**
     * <code>repeated .socketProtos.TgMatchInfo.BetDetail betDetail = 5;</code>
     */
    private void removeBetDetail(int index) {
      ensureBetDetailIsMutable();
      betDetail_.remove(index);
    }

    public static TgMatchInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static TgMatchInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static TgMatchInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static TgMatchInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static TgMatchInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static TgMatchInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static TgMatchInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static TgMatchInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static TgMatchInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static TgMatchInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static TgMatchInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static TgMatchInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(TgMatchInfo prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code socketProtos.TgMatchInfo.TgMatchInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          TgMatchInfo, Builder> implements
        // @@protoc_insertion_point(builder_implements:socketProtos.TgMatchInfo.TgMatchInfo)
        TgMatchInfoOrBuilder {
      // Construct using com.example.mvvm_navigation.protobuf.SocketTgMatchInfo.TgMatchInfo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * 賽事id
       * </pre>
       *
       * <code>int32 matchId = 1;</code>
       */
      @Override
      public int getMatchId() {
        return instance.getMatchId();
      }
      /**
       * <pre>
       * 賽事id
       * </pre>
       *
       * <code>int32 matchId = 1;</code>
       */
      public Builder setMatchId(int value) {
        copyOnWrite();
        instance.setMatchId(value);
        return this;
      }
      /**
       * <pre>
       * 賽事id
       * </pre>
       *
       * <code>int32 matchId = 1;</code>
       */
      public Builder clearMatchId() {
        copyOnWrite();
        instance.clearMatchId();
        return this;
      }

      /**
       * <pre>
       * TG賽事是否開啟 0未開啟 1開啟
       * </pre>
       *
       * <code>int32 tgStatus = 2;</code>
       */
      @Override
      public int getTgStatus() {
        return instance.getTgStatus();
      }
      /**
       * <pre>
       * TG賽事是否開啟 0未開啟 1開啟
       * </pre>
       *
       * <code>int32 tgStatus = 2;</code>
       */
      public Builder setTgStatus(int value) {
        copyOnWrite();
        instance.setTgStatus(value);
        return this;
      }
      /**
       * <pre>
       * TG賽事是否開啟 0未開啟 1開啟
       * </pre>
       *
       * <code>int32 tgStatus = 2;</code>
       */
      public Builder clearTgStatus() {
        copyOnWrite();
        instance.clearTgStatus();
        return this;
      }

      /**
       * <pre>
       * 開賽時間(timestamp)
       * </pre>
       *
       * <code>int32 openDate = 3;</code>
       */
      @Override
      public int getOpenDate() {
        return instance.getOpenDate();
      }
      /**
       * <pre>
       * 開賽時間(timestamp)
       * </pre>
       *
       * <code>int32 openDate = 3;</code>
       */
      public Builder setOpenDate(int value) {
        copyOnWrite();
        instance.setOpenDate(value);
        return this;
      }
      /**
       * <pre>
       * 開賽時間(timestamp)
       * </pre>
       *
       * <code>int32 openDate = 3;</code>
       */
      public Builder clearOpenDate() {
        copyOnWrite();
        instance.clearOpenDate();
        return this;
      }

      /**
       * <pre>
       * 總下注量
       * </pre>
       *
       * <code>int32 betsCount = 4;</code>
       */
      @Override
      public int getBetsCount() {
        return instance.getBetsCount();
      }
      /**
       * <pre>
       * 總下注量
       * </pre>
       *
       * <code>int32 betsCount = 4;</code>
       */
      public Builder setBetsCount(int value) {
        copyOnWrite();
        instance.setBetsCount(value);
        return this;
      }
      /**
       * <pre>
       * 總下注量
       * </pre>
       *
       * <code>int32 betsCount = 4;</code>
       */
      public Builder clearBetsCount() {
        copyOnWrite();
        instance.clearBetsCount();
        return this;
      }

      /**
       * <code>repeated .socketProtos.TgMatchInfo.BetDetail betDetail = 5;</code>
       */
      @Override
      public java.util.List<BetDetail> getBetDetailList() {
        return java.util.Collections.unmodifiableList(
            instance.getBetDetailList());
      }
      /**
       * <code>repeated .socketProtos.TgMatchInfo.BetDetail betDetail = 5;</code>
       */
      @Override
      public int getBetDetailCount() {
        return instance.getBetDetailCount();
      }/**
       * <code>repeated .socketProtos.TgMatchInfo.BetDetail betDetail = 5;</code>
       */
      @Override
      public BetDetail getBetDetail(int index) {
        return instance.getBetDetail(index);
      }
      /**
       * <code>repeated .socketProtos.TgMatchInfo.BetDetail betDetail = 5;</code>
       */
      public Builder setBetDetail(
          int index, BetDetail value) {
        copyOnWrite();
        instance.setBetDetail(index, value);
        return this;
      }
      /**
       * <code>repeated .socketProtos.TgMatchInfo.BetDetail betDetail = 5;</code>
       */
      public Builder setBetDetail(
          int index, BetDetail.Builder builderForValue) {
        copyOnWrite();
        instance.setBetDetail(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .socketProtos.TgMatchInfo.BetDetail betDetail = 5;</code>
       */
      public Builder addBetDetail(BetDetail value) {
        copyOnWrite();
        instance.addBetDetail(value);
        return this;
      }
      /**
       * <code>repeated .socketProtos.TgMatchInfo.BetDetail betDetail = 5;</code>
       */
      public Builder addBetDetail(
          int index, BetDetail value) {
        copyOnWrite();
        instance.addBetDetail(index, value);
        return this;
      }
      /**
       * <code>repeated .socketProtos.TgMatchInfo.BetDetail betDetail = 5;</code>
       */
      public Builder addBetDetail(
          BetDetail.Builder builderForValue) {
        copyOnWrite();
        instance.addBetDetail(builderForValue);
        return this;
      }
      /**
       * <code>repeated .socketProtos.TgMatchInfo.BetDetail betDetail = 5;</code>
       */
      public Builder addBetDetail(
          int index, BetDetail.Builder builderForValue) {
        copyOnWrite();
        instance.addBetDetail(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .socketProtos.TgMatchInfo.BetDetail betDetail = 5;</code>
       */
      public Builder addAllBetDetail(
          Iterable<? extends BetDetail> values) {
        copyOnWrite();
        instance.addAllBetDetail(values);
        return this;
      }
      /**
       * <code>repeated .socketProtos.TgMatchInfo.BetDetail betDetail = 5;</code>
       */
      public Builder clearBetDetail() {
        copyOnWrite();
        instance.clearBetDetail();
        return this;
      }
      /**
       * <code>repeated .socketProtos.TgMatchInfo.BetDetail betDetail = 5;</code>
       */
      public Builder removeBetDetail(int index) {
        copyOnWrite();
        instance.removeBetDetail(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:socketProtos.TgMatchInfo.TgMatchInfo)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new TgMatchInfo();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "matchId_",
              "tgStatus_",
              "openDate_",
              "betsCount_",
              "betDetail_",
              BetDetail.class,
            };
            String info =
                "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0001\u0000\u0001\u0004\u0002\u0004" +
                "\u0003\u0004\u0004\u0004\u0005\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<TgMatchInfo> parser = PARSER;
          if (parser == null) {
            synchronized (TgMatchInfo.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:socketProtos.TgMatchInfo.TgMatchInfo)
    private static final TgMatchInfo DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new TgMatchInfo();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        TgMatchInfo.class, DEFAULT_INSTANCE);
    }
    public static TgMatchInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<TgMatchInfo> PARSER;

    public static com.google.protobuf.Parser<TgMatchInfo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface BetDetailOrBuilder extends
      // @@protoc_insertion_point(interface_extends:socketProtos.TgMatchInfo.BetDetail)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * 1波膽 2半場波膽 3總入球
     * </pre>
     *
     * <code>int32 marketType = 1;</code>
     */
    int getMarketType();

    /**
     * <pre>
     * 選項名稱
     * </pre>
     *
     * <code>string selectionName = 2;</code>
     */
    String getSelectionName();
    /**
     * <pre>
     * 選項名稱
     * </pre>
     *
     * <code>string selectionName = 2;</code>
     */
    com.google.protobuf.ByteString
        getSelectionNameBytes();

    /**
     * <pre>
     * 可交易量
     * </pre>
     *
     * <code>string transaction = 3;</code>
     */
    String getTransaction();
    /**
     * <pre>
     * 可交易量
     * </pre>
     *
     * <code>string transaction = 3;</code>
     */
    com.google.protobuf.ByteString
        getTransactionBytes();

    /**
     * <pre>
     * 獲利率
     * </pre>
     *
     * <code>string profit = 4;</code>
     */
    String getProfit();
    /**
     * <pre>
     * 獲利率
     * </pre>
     *
     * <code>string profit = 4;</code>
     */
    com.google.protobuf.ByteString
        getProfitBytes();

    /**
     * <pre>
     * 累積金額
     * </pre>
     *
     * <code>string betMoney = 5;</code>
     */
    String getBetMoney();
    /**
     * <pre>
     * 累積金額
     * </pre>
     *
     * <code>string betMoney = 5;</code>
     */
    com.google.protobuf.ByteString
        getBetMoneyBytes();

    /**
     * <pre>
     * 是否熱銷
     * </pre>
     *
     * <code>int32 isPopular = 6;</code>
     */
    int getIsPopular();

    /**
     * <pre>
     * 是否完售
     * </pre>
     *
     * <code>int32 isSoldOut = 7;</code>
     */
    int getIsSoldOut();
  }
  /**
   * Protobuf type {@code socketProtos.TgMatchInfo.BetDetail}
   */
  public  static final class BetDetail extends
      com.google.protobuf.GeneratedMessageLite<
          BetDetail, BetDetail.Builder> implements
      // @@protoc_insertion_point(message_implements:socketProtos.TgMatchInfo.BetDetail)
      BetDetailOrBuilder {
    private BetDetail() {
      selectionName_ = "";
      transaction_ = "";
      profit_ = "";
      betMoney_ = "";
    }
    public static final int MARKETTYPE_FIELD_NUMBER = 1;
    private int marketType_;
    /**
     * <pre>
     * 1波膽 2半場波膽 3總入球
     * </pre>
     *
     * <code>int32 marketType = 1;</code>
     */
    @Override
    public int getMarketType() {
      return marketType_;
    }
    /**
     * <pre>
     * 1波膽 2半場波膽 3總入球
     * </pre>
     *
     * <code>int32 marketType = 1;</code>
     */
    private void setMarketType(int value) {
      
      marketType_ = value;
    }
    /**
     * <pre>
     * 1波膽 2半場波膽 3總入球
     * </pre>
     *
     * <code>int32 marketType = 1;</code>
     */
    private void clearMarketType() {
      
      marketType_ = 0;
    }

    public static final int SELECTIONNAME_FIELD_NUMBER = 2;
    private String selectionName_;
    /**
     * <pre>
     * 選項名稱
     * </pre>
     *
     * <code>string selectionName = 2;</code>
     */
    @Override
    public String getSelectionName() {
      return selectionName_;
    }
    /**
     * <pre>
     * 選項名稱
     * </pre>
     *
     * <code>string selectionName = 2;</code>
     */
    @Override
    public com.google.protobuf.ByteString
        getSelectionNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(selectionName_);
    }
    /**
     * <pre>
     * 選項名稱
     * </pre>
     *
     * <code>string selectionName = 2;</code>
     */
    private void setSelectionName(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      selectionName_ = value;
    }
    /**
     * <pre>
     * 選項名稱
     * </pre>
     *
     * <code>string selectionName = 2;</code>
     */
    private void clearSelectionName() {
      
      selectionName_ = getDefaultInstance().getSelectionName();
    }
    /**
     * <pre>
     * 選項名稱
     * </pre>
     *
     * <code>string selectionName = 2;</code>
     */
    private void setSelectionNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      selectionName_ = value.toStringUtf8();
    }

    public static final int TRANSACTION_FIELD_NUMBER = 3;
    private String transaction_;
    /**
     * <pre>
     * 可交易量
     * </pre>
     *
     * <code>string transaction = 3;</code>
     */
    @Override
    public String getTransaction() {
      return transaction_;
    }
    /**
     * <pre>
     * 可交易量
     * </pre>
     *
     * <code>string transaction = 3;</code>
     */
    @Override
    public com.google.protobuf.ByteString
        getTransactionBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(transaction_);
    }
    /**
     * <pre>
     * 可交易量
     * </pre>
     *
     * <code>string transaction = 3;</code>
     */
    private void setTransaction(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      transaction_ = value;
    }
    /**
     * <pre>
     * 可交易量
     * </pre>
     *
     * <code>string transaction = 3;</code>
     */
    private void clearTransaction() {
      
      transaction_ = getDefaultInstance().getTransaction();
    }
    /**
     * <pre>
     * 可交易量
     * </pre>
     *
     * <code>string transaction = 3;</code>
     */
    private void setTransactionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      transaction_ = value.toStringUtf8();
    }

    public static final int PROFIT_FIELD_NUMBER = 4;
    private String profit_;
    /**
     * <pre>
     * 獲利率
     * </pre>
     *
     * <code>string profit = 4;</code>
     */
    @Override
    public String getProfit() {
      return profit_;
    }
    /**
     * <pre>
     * 獲利率
     * </pre>
     *
     * <code>string profit = 4;</code>
     */
    @Override
    public com.google.protobuf.ByteString
        getProfitBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(profit_);
    }
    /**
     * <pre>
     * 獲利率
     * </pre>
     *
     * <code>string profit = 4;</code>
     */
    private void setProfit(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      profit_ = value;
    }
    /**
     * <pre>
     * 獲利率
     * </pre>
     *
     * <code>string profit = 4;</code>
     */
    private void clearProfit() {
      
      profit_ = getDefaultInstance().getProfit();
    }
    /**
     * <pre>
     * 獲利率
     * </pre>
     *
     * <code>string profit = 4;</code>
     */
    private void setProfitBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      profit_ = value.toStringUtf8();
    }

    public static final int BETMONEY_FIELD_NUMBER = 5;
    private String betMoney_;
    /**
     * <pre>
     * 累積金額
     * </pre>
     *
     * <code>string betMoney = 5;</code>
     */
    @Override
    public String getBetMoney() {
      return betMoney_;
    }
    /**
     * <pre>
     * 累積金額
     * </pre>
     *
     * <code>string betMoney = 5;</code>
     */
    @Override
    public com.google.protobuf.ByteString
        getBetMoneyBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(betMoney_);
    }
    /**
     * <pre>
     * 累積金額
     * </pre>
     *
     * <code>string betMoney = 5;</code>
     */
    private void setBetMoney(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      betMoney_ = value;
    }
    /**
     * <pre>
     * 累積金額
     * </pre>
     *
     * <code>string betMoney = 5;</code>
     */
    private void clearBetMoney() {
      
      betMoney_ = getDefaultInstance().getBetMoney();
    }
    /**
     * <pre>
     * 累積金額
     * </pre>
     *
     * <code>string betMoney = 5;</code>
     */
    private void setBetMoneyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      betMoney_ = value.toStringUtf8();
    }

    public static final int ISPOPULAR_FIELD_NUMBER = 6;
    private int isPopular_;
    /**
     * <pre>
     * 是否熱銷
     * </pre>
     *
     * <code>int32 isPopular = 6;</code>
     */
    @Override
    public int getIsPopular() {
      return isPopular_;
    }
    /**
     * <pre>
     * 是否熱銷
     * </pre>
     *
     * <code>int32 isPopular = 6;</code>
     */
    private void setIsPopular(int value) {
      
      isPopular_ = value;
    }
    /**
     * <pre>
     * 是否熱銷
     * </pre>
     *
     * <code>int32 isPopular = 6;</code>
     */
    private void clearIsPopular() {
      
      isPopular_ = 0;
    }

    public static final int ISSOLDOUT_FIELD_NUMBER = 7;
    private int isSoldOut_;
    /**
     * <pre>
     * 是否完售
     * </pre>
     *
     * <code>int32 isSoldOut = 7;</code>
     */
    @Override
    public int getIsSoldOut() {
      return isSoldOut_;
    }
    /**
     * <pre>
     * 是否完售
     * </pre>
     *
     * <code>int32 isSoldOut = 7;</code>
     */
    private void setIsSoldOut(int value) {
      
      isSoldOut_ = value;
    }
    /**
     * <pre>
     * 是否完售
     * </pre>
     *
     * <code>int32 isSoldOut = 7;</code>
     */
    private void clearIsSoldOut() {
      
      isSoldOut_ = 0;
    }

    public static BetDetail parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static BetDetail parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static BetDetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static BetDetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static BetDetail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static BetDetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static BetDetail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static BetDetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static BetDetail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static BetDetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static BetDetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static BetDetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(BetDetail prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code socketProtos.TgMatchInfo.BetDetail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          BetDetail, Builder> implements
        // @@protoc_insertion_point(builder_implements:socketProtos.TgMatchInfo.BetDetail)
        BetDetailOrBuilder {
      // Construct using com.example.mvvm_navigation.protobuf.SocketTgMatchInfo.BetDetail.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * 1波膽 2半場波膽 3總入球
       * </pre>
       *
       * <code>int32 marketType = 1;</code>
       */
      @Override
      public int getMarketType() {
        return instance.getMarketType();
      }
      /**
       * <pre>
       * 1波膽 2半場波膽 3總入球
       * </pre>
       *
       * <code>int32 marketType = 1;</code>
       */
      public Builder setMarketType(int value) {
        copyOnWrite();
        instance.setMarketType(value);
        return this;
      }
      /**
       * <pre>
       * 1波膽 2半場波膽 3總入球
       * </pre>
       *
       * <code>int32 marketType = 1;</code>
       */
      public Builder clearMarketType() {
        copyOnWrite();
        instance.clearMarketType();
        return this;
      }

      /**
       * <pre>
       * 選項名稱
       * </pre>
       *
       * <code>string selectionName = 2;</code>
       */
      @Override
      public String getSelectionName() {
        return instance.getSelectionName();
      }
      /**
       * <pre>
       * 選項名稱
       * </pre>
       *
       * <code>string selectionName = 2;</code>
       */
      @Override
      public com.google.protobuf.ByteString
          getSelectionNameBytes() {
        return instance.getSelectionNameBytes();
      }
      /**
       * <pre>
       * 選項名稱
       * </pre>
       *
       * <code>string selectionName = 2;</code>
       */
      public Builder setSelectionName(
          String value) {
        copyOnWrite();
        instance.setSelectionName(value);
        return this;
      }
      /**
       * <pre>
       * 選項名稱
       * </pre>
       *
       * <code>string selectionName = 2;</code>
       */
      public Builder clearSelectionName() {
        copyOnWrite();
        instance.clearSelectionName();
        return this;
      }
      /**
       * <pre>
       * 選項名稱
       * </pre>
       *
       * <code>string selectionName = 2;</code>
       */
      public Builder setSelectionNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSelectionNameBytes(value);
        return this;
      }

      /**
       * <pre>
       * 可交易量
       * </pre>
       *
       * <code>string transaction = 3;</code>
       */
      @Override
      public String getTransaction() {
        return instance.getTransaction();
      }
      /**
       * <pre>
       * 可交易量
       * </pre>
       *
       * <code>string transaction = 3;</code>
       */
      @Override
      public com.google.protobuf.ByteString
          getTransactionBytes() {
        return instance.getTransactionBytes();
      }
      /**
       * <pre>
       * 可交易量
       * </pre>
       *
       * <code>string transaction = 3;</code>
       */
      public Builder setTransaction(
          String value) {
        copyOnWrite();
        instance.setTransaction(value);
        return this;
      }
      /**
       * <pre>
       * 可交易量
       * </pre>
       *
       * <code>string transaction = 3;</code>
       */
      public Builder clearTransaction() {
        copyOnWrite();
        instance.clearTransaction();
        return this;
      }
      /**
       * <pre>
       * 可交易量
       * </pre>
       *
       * <code>string transaction = 3;</code>
       */
      public Builder setTransactionBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTransactionBytes(value);
        return this;
      }

      /**
       * <pre>
       * 獲利率
       * </pre>
       *
       * <code>string profit = 4;</code>
       */
      @Override
      public String getProfit() {
        return instance.getProfit();
      }
      /**
       * <pre>
       * 獲利率
       * </pre>
       *
       * <code>string profit = 4;</code>
       */
      @Override
      public com.google.protobuf.ByteString
          getProfitBytes() {
        return instance.getProfitBytes();
      }
      /**
       * <pre>
       * 獲利率
       * </pre>
       *
       * <code>string profit = 4;</code>
       */
      public Builder setProfit(
          String value) {
        copyOnWrite();
        instance.setProfit(value);
        return this;
      }
      /**
       * <pre>
       * 獲利率
       * </pre>
       *
       * <code>string profit = 4;</code>
       */
      public Builder clearProfit() {
        copyOnWrite();
        instance.clearProfit();
        return this;
      }
      /**
       * <pre>
       * 獲利率
       * </pre>
       *
       * <code>string profit = 4;</code>
       */
      public Builder setProfitBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setProfitBytes(value);
        return this;
      }

      /**
       * <pre>
       * 累積金額
       * </pre>
       *
       * <code>string betMoney = 5;</code>
       */
      @Override
      public String getBetMoney() {
        return instance.getBetMoney();
      }
      /**
       * <pre>
       * 累積金額
       * </pre>
       *
       * <code>string betMoney = 5;</code>
       */
      @Override
      public com.google.protobuf.ByteString
          getBetMoneyBytes() {
        return instance.getBetMoneyBytes();
      }
      /**
       * <pre>
       * 累積金額
       * </pre>
       *
       * <code>string betMoney = 5;</code>
       */
      public Builder setBetMoney(
          String value) {
        copyOnWrite();
        instance.setBetMoney(value);
        return this;
      }
      /**
       * <pre>
       * 累積金額
       * </pre>
       *
       * <code>string betMoney = 5;</code>
       */
      public Builder clearBetMoney() {
        copyOnWrite();
        instance.clearBetMoney();
        return this;
      }
      /**
       * <pre>
       * 累積金額
       * </pre>
       *
       * <code>string betMoney = 5;</code>
       */
      public Builder setBetMoneyBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setBetMoneyBytes(value);
        return this;
      }

      /**
       * <pre>
       * 是否熱銷
       * </pre>
       *
       * <code>int32 isPopular = 6;</code>
       */
      @Override
      public int getIsPopular() {
        return instance.getIsPopular();
      }
      /**
       * <pre>
       * 是否熱銷
       * </pre>
       *
       * <code>int32 isPopular = 6;</code>
       */
      public Builder setIsPopular(int value) {
        copyOnWrite();
        instance.setIsPopular(value);
        return this;
      }
      /**
       * <pre>
       * 是否熱銷
       * </pre>
       *
       * <code>int32 isPopular = 6;</code>
       */
      public Builder clearIsPopular() {
        copyOnWrite();
        instance.clearIsPopular();
        return this;
      }

      /**
       * <pre>
       * 是否完售
       * </pre>
       *
       * <code>int32 isSoldOut = 7;</code>
       */
      @Override
      public int getIsSoldOut() {
        return instance.getIsSoldOut();
      }
      /**
       * <pre>
       * 是否完售
       * </pre>
       *
       * <code>int32 isSoldOut = 7;</code>
       */
      public Builder setIsSoldOut(int value) {
        copyOnWrite();
        instance.setIsSoldOut(value);
        return this;
      }
      /**
       * <pre>
       * 是否完售
       * </pre>
       *
       * <code>int32 isSoldOut = 7;</code>
       */
      public Builder clearIsSoldOut() {
        copyOnWrite();
        instance.clearIsSoldOut();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:socketProtos.TgMatchInfo.BetDetail)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new BetDetail();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "marketType_",
              "selectionName_",
              "transaction_",
              "profit_",
              "betMoney_",
              "isPopular_",
              "isSoldOut_",
            };
            String info =
                "\u0000\u0007\u0000\u0000\u0001\u0007\u0007\u0000\u0000\u0000\u0001\u0004\u0002\u0208" +
                "\u0003\u0208\u0004\u0208\u0005\u0208\u0006\u0004\u0007\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<BetDetail> parser = PARSER;
          if (parser == null) {
            synchronized (BetDetail.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:socketProtos.TgMatchInfo.BetDetail)
    private static final BetDetail DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new BetDetail();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        BetDetail.class, DEFAULT_INSTANCE);
    }
    public static BetDetail getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<BetDetail> PARSER;

    public static com.google.protobuf.Parser<BetDetail> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
