// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IndexOdds.proto

package com.example.mvvm_navigation.protobuf;

public final class SocketIndexOdds {
  private SocketIndexOdds() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface IndexUpdateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:socketProtos.IndexOdds.IndexUpdate)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.socketProtos.command.Command command = 1;</code>
     */
    int getCommandValue();
    /**
     * <code>.socketProtos.command.Command command = 1;</code>
     */
    Socket.Command getCommand();

    /**
     * <code>repeated .socketProtos.IndexOdds.IndexInfo data = 2;</code>
     */
    java.util.List<IndexInfo>
        getDataList();
    /**
     * <code>repeated .socketProtos.IndexOdds.IndexInfo data = 2;</code>
     */
    IndexInfo getData(int index);
    /**
     * <code>repeated .socketProtos.IndexOdds.IndexInfo data = 2;</code>
     */
    int getDataCount();
  }
  /**
   * Protobuf type {@code socketProtos.IndexOdds.IndexUpdate}
   */
  public  static final class IndexUpdate extends
      com.google.protobuf.GeneratedMessageLite<
          IndexUpdate, IndexUpdate.Builder> implements
      // @@protoc_insertion_point(message_implements:socketProtos.IndexOdds.IndexUpdate)
      IndexUpdateOrBuilder {
    private IndexUpdate() {
      data_ = emptyProtobufList();
    }
    public static final int COMMAND_FIELD_NUMBER = 1;
    private int command_;
    /**
     * <code>.socketProtos.command.Command command = 1;</code>
     */
    @Override
    public int getCommandValue() {
      return command_;
    }
    /**
     * <code>.socketProtos.command.Command command = 1;</code>
     */
    @Override
    public Socket.Command getCommand() {
      Socket.Command result = Socket.Command.forNumber(command_);
      return result == null ? Socket.Command.UNRECOGNIZED : result;
    }
    /**
     * <code>.socketProtos.command.Command command = 1;</code>
     */
    private void setCommandValue(int value) {
        command_ = value;
    }
    /**
     * <code>.socketProtos.command.Command command = 1;</code>
     */
    private void setCommand(Socket.Command value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      command_ = value.getNumber();
    }
    /**
     * <code>.socketProtos.command.Command command = 1;</code>
     */
    private void clearCommand() {
      
      command_ = 0;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<IndexInfo> data_;
    /**
     * <code>repeated .socketProtos.IndexOdds.IndexInfo data = 2;</code>
     */
    @Override
    public java.util.List<IndexInfo> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .socketProtos.IndexOdds.IndexInfo data = 2;</code>
     */
    public java.util.List<? extends IndexInfoOrBuilder>
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .socketProtos.IndexOdds.IndexInfo data = 2;</code>
     */
    @Override
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .socketProtos.IndexOdds.IndexInfo data = 2;</code>
     */
    @Override
    public IndexInfo getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .socketProtos.IndexOdds.IndexInfo data = 2;</code>
     */
    public IndexInfoOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }
    private void ensureDataIsMutable() {
      if (!data_.isModifiable()) {
        data_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(data_);
       }
    }

    /**
     * <code>repeated .socketProtos.IndexOdds.IndexInfo data = 2;</code>
     */
    private void setData(
        int index, IndexInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureDataIsMutable();
      data_.set(index, value);
    }
    /**
     * <code>repeated .socketProtos.IndexOdds.IndexInfo data = 2;</code>
     */
    private void setData(
        int index, IndexInfo.Builder builderForValue) {
      ensureDataIsMutable();
      data_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .socketProtos.IndexOdds.IndexInfo data = 2;</code>
     */
    private void addData(IndexInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureDataIsMutable();
      data_.add(value);
    }
    /**
     * <code>repeated .socketProtos.IndexOdds.IndexInfo data = 2;</code>
     */
    private void addData(
        int index, IndexInfo value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureDataIsMutable();
      data_.add(index, value);
    }
    /**
     * <code>repeated .socketProtos.IndexOdds.IndexInfo data = 2;</code>
     */
    private void addData(
        IndexInfo.Builder builderForValue) {
      ensureDataIsMutable();
      data_.add(builderForValue.build());
    }
    /**
     * <code>repeated .socketProtos.IndexOdds.IndexInfo data = 2;</code>
     */
    private void addData(
        int index, IndexInfo.Builder builderForValue) {
      ensureDataIsMutable();
      data_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .socketProtos.IndexOdds.IndexInfo data = 2;</code>
     */
    private void addAllData(
        Iterable<? extends IndexInfo> values) {
      ensureDataIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, data_);
    }
    /**
     * <code>repeated .socketProtos.IndexOdds.IndexInfo data = 2;</code>
     */
    private void clearData() {
      data_ = emptyProtobufList();
    }
    /**
     * <code>repeated .socketProtos.IndexOdds.IndexInfo data = 2;</code>
     */
    private void removeData(int index) {
      ensureDataIsMutable();
      data_.remove(index);
    }

    public static IndexUpdate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static IndexUpdate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static IndexUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static IndexUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static IndexUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static IndexUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static IndexUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static IndexUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static IndexUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static IndexUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static IndexUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static IndexUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(IndexUpdate prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code socketProtos.IndexOdds.IndexUpdate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          IndexUpdate, Builder> implements
        // @@protoc_insertion_point(builder_implements:socketProtos.IndexOdds.IndexUpdate)
        IndexUpdateOrBuilder {
      // Construct using com.example.mvvm_navigation.protobuf.SocketIndexOdds.IndexUpdate.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.socketProtos.command.Command command = 1;</code>
       */
      @Override
      public int getCommandValue() {
        return instance.getCommandValue();
      }
      /**
       * <code>.socketProtos.command.Command command = 1;</code>
       */
      public Builder setCommandValue(int value) {
        copyOnWrite();
        instance.setCommandValue(value);
        return this;
      }
      /**
       * <code>.socketProtos.command.Command command = 1;</code>
       */
      @Override
      public Socket.Command getCommand() {
        return instance.getCommand();
      }
      /**
       * <code>.socketProtos.command.Command command = 1;</code>
       */
      public Builder setCommand(Socket.Command value) {
        copyOnWrite();
        instance.setCommand(value);
        return this;
      }
      /**
       * <code>.socketProtos.command.Command command = 1;</code>
       */
      public Builder clearCommand() {
        copyOnWrite();
        instance.clearCommand();
        return this;
      }

      /**
       * <code>repeated .socketProtos.IndexOdds.IndexInfo data = 2;</code>
       */
      @Override
      public java.util.List<IndexInfo> getDataList() {
        return java.util.Collections.unmodifiableList(
            instance.getDataList());
      }
      /**
       * <code>repeated .socketProtos.IndexOdds.IndexInfo data = 2;</code>
       */
      @Override
      public int getDataCount() {
        return instance.getDataCount();
      }/**
       * <code>repeated .socketProtos.IndexOdds.IndexInfo data = 2;</code>
       */
      @Override
      public IndexInfo getData(int index) {
        return instance.getData(index);
      }
      /**
       * <code>repeated .socketProtos.IndexOdds.IndexInfo data = 2;</code>
       */
      public Builder setData(
          int index, IndexInfo value) {
        copyOnWrite();
        instance.setData(index, value);
        return this;
      }
      /**
       * <code>repeated .socketProtos.IndexOdds.IndexInfo data = 2;</code>
       */
      public Builder setData(
          int index, IndexInfo.Builder builderForValue) {
        copyOnWrite();
        instance.setData(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .socketProtos.IndexOdds.IndexInfo data = 2;</code>
       */
      public Builder addData(IndexInfo value) {
        copyOnWrite();
        instance.addData(value);
        return this;
      }
      /**
       * <code>repeated .socketProtos.IndexOdds.IndexInfo data = 2;</code>
       */
      public Builder addData(
          int index, IndexInfo value) {
        copyOnWrite();
        instance.addData(index, value);
        return this;
      }
      /**
       * <code>repeated .socketProtos.IndexOdds.IndexInfo data = 2;</code>
       */
      public Builder addData(
          IndexInfo.Builder builderForValue) {
        copyOnWrite();
        instance.addData(builderForValue);
        return this;
      }
      /**
       * <code>repeated .socketProtos.IndexOdds.IndexInfo data = 2;</code>
       */
      public Builder addData(
          int index, IndexInfo.Builder builderForValue) {
        copyOnWrite();
        instance.addData(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .socketProtos.IndexOdds.IndexInfo data = 2;</code>
       */
      public Builder addAllData(
          Iterable<? extends IndexInfo> values) {
        copyOnWrite();
        instance.addAllData(values);
        return this;
      }
      /**
       * <code>repeated .socketProtos.IndexOdds.IndexInfo data = 2;</code>
       */
      public Builder clearData() {
        copyOnWrite();
        instance.clearData();
        return this;
      }
      /**
       * <code>repeated .socketProtos.IndexOdds.IndexInfo data = 2;</code>
       */
      public Builder removeData(int index) {
        copyOnWrite();
        instance.removeData(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:socketProtos.IndexOdds.IndexUpdate)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new IndexUpdate();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "command_",
              "data_",
              IndexInfo.class,
            };
            String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\f\u0002\u001b" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<IndexUpdate> parser = PARSER;
          if (parser == null) {
            synchronized (IndexUpdate.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:socketProtos.IndexOdds.IndexUpdate)
    private static final IndexUpdate DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new IndexUpdate();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        IndexUpdate.class, DEFAULT_INSTANCE);
    }
    public static IndexUpdate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<IndexUpdate> PARSER;

    public static com.google.protobuf.Parser<IndexUpdate> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface IndexInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:socketProtos.IndexOdds.IndexInfo)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * 賽事id
     * </pre>
     *
     * <code>int32 matchId = 1;</code>
     */
    int getMatchId();

    /**
     * <pre>
     * 盤口資訊
     * </pre>
     *
     * <code>repeated .socketProtos.IndexOdds.Odds odds = 2;</code>
     */
    java.util.List<Odds>
        getOddsList();
    /**
     * <pre>
     * 盤口資訊
     * </pre>
     *
     * <code>repeated .socketProtos.IndexOdds.Odds odds = 2;</code>
     */
    Odds getOdds(int index);
    /**
     * <pre>
     * 盤口資訊
     * </pre>
     *
     * <code>repeated .socketProtos.IndexOdds.Odds odds = 2;</code>
     */
    int getOddsCount();
  }
  /**
   * Protobuf type {@code socketProtos.IndexOdds.IndexInfo}
   */
  public  static final class IndexInfo extends
      com.google.protobuf.GeneratedMessageLite<
          IndexInfo, IndexInfo.Builder> implements
      // @@protoc_insertion_point(message_implements:socketProtos.IndexOdds.IndexInfo)
      IndexInfoOrBuilder {
    private IndexInfo() {
      odds_ = emptyProtobufList();
    }
    public static final int MATCHID_FIELD_NUMBER = 1;
    private int matchId_;
    /**
     * <pre>
     * 賽事id
     * </pre>
     *
     * <code>int32 matchId = 1;</code>
     */
    @Override
    public int getMatchId() {
      return matchId_;
    }
    /**
     * <pre>
     * 賽事id
     * </pre>
     *
     * <code>int32 matchId = 1;</code>
     */
    private void setMatchId(int value) {
      
      matchId_ = value;
    }
    /**
     * <pre>
     * 賽事id
     * </pre>
     *
     * <code>int32 matchId = 1;</code>
     */
    private void clearMatchId() {
      
      matchId_ = 0;
    }

    public static final int ODDS_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<Odds> odds_;
    /**
     * <pre>
     * 盤口資訊
     * </pre>
     *
     * <code>repeated .socketProtos.IndexOdds.Odds odds = 2;</code>
     */
    @Override
    public java.util.List<Odds> getOddsList() {
      return odds_;
    }
    /**
     * <pre>
     * 盤口資訊
     * </pre>
     *
     * <code>repeated .socketProtos.IndexOdds.Odds odds = 2;</code>
     */
    public java.util.List<? extends OddsOrBuilder>
        getOddsOrBuilderList() {
      return odds_;
    }
    /**
     * <pre>
     * 盤口資訊
     * </pre>
     *
     * <code>repeated .socketProtos.IndexOdds.Odds odds = 2;</code>
     */
    @Override
    public int getOddsCount() {
      return odds_.size();
    }
    /**
     * <pre>
     * 盤口資訊
     * </pre>
     *
     * <code>repeated .socketProtos.IndexOdds.Odds odds = 2;</code>
     */
    @Override
    public Odds getOdds(int index) {
      return odds_.get(index);
    }
    /**
     * <pre>
     * 盤口資訊
     * </pre>
     *
     * <code>repeated .socketProtos.IndexOdds.Odds odds = 2;</code>
     */
    public OddsOrBuilder getOddsOrBuilder(
        int index) {
      return odds_.get(index);
    }
    private void ensureOddsIsMutable() {
      if (!odds_.isModifiable()) {
        odds_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(odds_);
       }
    }

    /**
     * <pre>
     * 盤口資訊
     * </pre>
     *
     * <code>repeated .socketProtos.IndexOdds.Odds odds = 2;</code>
     */
    private void setOdds(
        int index, Odds value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureOddsIsMutable();
      odds_.set(index, value);
    }
    /**
     * <pre>
     * 盤口資訊
     * </pre>
     *
     * <code>repeated .socketProtos.IndexOdds.Odds odds = 2;</code>
     */
    private void setOdds(
        int index, Odds.Builder builderForValue) {
      ensureOddsIsMutable();
      odds_.set(index, builderForValue.build());
    }
    /**
     * <pre>
     * 盤口資訊
     * </pre>
     *
     * <code>repeated .socketProtos.IndexOdds.Odds odds = 2;</code>
     */
    private void addOdds(Odds value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureOddsIsMutable();
      odds_.add(value);
    }
    /**
     * <pre>
     * 盤口資訊
     * </pre>
     *
     * <code>repeated .socketProtos.IndexOdds.Odds odds = 2;</code>
     */
    private void addOdds(
        int index, Odds value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureOddsIsMutable();
      odds_.add(index, value);
    }
    /**
     * <pre>
     * 盤口資訊
     * </pre>
     *
     * <code>repeated .socketProtos.IndexOdds.Odds odds = 2;</code>
     */
    private void addOdds(
        Odds.Builder builderForValue) {
      ensureOddsIsMutable();
      odds_.add(builderForValue.build());
    }
    /**
     * <pre>
     * 盤口資訊
     * </pre>
     *
     * <code>repeated .socketProtos.IndexOdds.Odds odds = 2;</code>
     */
    private void addOdds(
        int index, Odds.Builder builderForValue) {
      ensureOddsIsMutable();
      odds_.add(index, builderForValue.build());
    }
    /**
     * <pre>
     * 盤口資訊
     * </pre>
     *
     * <code>repeated .socketProtos.IndexOdds.Odds odds = 2;</code>
     */
    private void addAllOdds(
        Iterable<? extends Odds> values) {
      ensureOddsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, odds_);
    }
    /**
     * <pre>
     * 盤口資訊
     * </pre>
     *
     * <code>repeated .socketProtos.IndexOdds.Odds odds = 2;</code>
     */
    private void clearOdds() {
      odds_ = emptyProtobufList();
    }
    /**
     * <pre>
     * 盤口資訊
     * </pre>
     *
     * <code>repeated .socketProtos.IndexOdds.Odds odds = 2;</code>
     */
    private void removeOdds(int index) {
      ensureOddsIsMutable();
      odds_.remove(index);
    }

    public static IndexInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static IndexInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static IndexInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static IndexInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static IndexInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static IndexInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static IndexInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static IndexInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static IndexInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static IndexInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static IndexInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static IndexInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(IndexInfo prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code socketProtos.IndexOdds.IndexInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          IndexInfo, Builder> implements
        // @@protoc_insertion_point(builder_implements:socketProtos.IndexOdds.IndexInfo)
        IndexInfoOrBuilder {
      // Construct using com.example.mvvm_navigation.protobuf.SocketIndexOdds.IndexInfo.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * 賽事id
       * </pre>
       *
       * <code>int32 matchId = 1;</code>
       */
      @Override
      public int getMatchId() {
        return instance.getMatchId();
      }
      /**
       * <pre>
       * 賽事id
       * </pre>
       *
       * <code>int32 matchId = 1;</code>
       */
      public Builder setMatchId(int value) {
        copyOnWrite();
        instance.setMatchId(value);
        return this;
      }
      /**
       * <pre>
       * 賽事id
       * </pre>
       *
       * <code>int32 matchId = 1;</code>
       */
      public Builder clearMatchId() {
        copyOnWrite();
        instance.clearMatchId();
        return this;
      }

      /**
       * <pre>
       * 盤口資訊
       * </pre>
       *
       * <code>repeated .socketProtos.IndexOdds.Odds odds = 2;</code>
       */
      @Override
      public java.util.List<Odds> getOddsList() {
        return java.util.Collections.unmodifiableList(
            instance.getOddsList());
      }
      /**
       * <pre>
       * 盤口資訊
       * </pre>
       *
       * <code>repeated .socketProtos.IndexOdds.Odds odds = 2;</code>
       */
      @Override
      public int getOddsCount() {
        return instance.getOddsCount();
      }/**
       * <pre>
       * 盤口資訊
       * </pre>
       *
       * <code>repeated .socketProtos.IndexOdds.Odds odds = 2;</code>
       */
      @Override
      public Odds getOdds(int index) {
        return instance.getOdds(index);
      }
      /**
       * <pre>
       * 盤口資訊
       * </pre>
       *
       * <code>repeated .socketProtos.IndexOdds.Odds odds = 2;</code>
       */
      public Builder setOdds(
          int index, Odds value) {
        copyOnWrite();
        instance.setOdds(index, value);
        return this;
      }
      /**
       * <pre>
       * 盤口資訊
       * </pre>
       *
       * <code>repeated .socketProtos.IndexOdds.Odds odds = 2;</code>
       */
      public Builder setOdds(
          int index, Odds.Builder builderForValue) {
        copyOnWrite();
        instance.setOdds(index, builderForValue);
        return this;
      }
      /**
       * <pre>
       * 盤口資訊
       * </pre>
       *
       * <code>repeated .socketProtos.IndexOdds.Odds odds = 2;</code>
       */
      public Builder addOdds(Odds value) {
        copyOnWrite();
        instance.addOdds(value);
        return this;
      }
      /**
       * <pre>
       * 盤口資訊
       * </pre>
       *
       * <code>repeated .socketProtos.IndexOdds.Odds odds = 2;</code>
       */
      public Builder addOdds(
          int index, Odds value) {
        copyOnWrite();
        instance.addOdds(index, value);
        return this;
      }
      /**
       * <pre>
       * 盤口資訊
       * </pre>
       *
       * <code>repeated .socketProtos.IndexOdds.Odds odds = 2;</code>
       */
      public Builder addOdds(
          Odds.Builder builderForValue) {
        copyOnWrite();
        instance.addOdds(builderForValue);
        return this;
      }
      /**
       * <pre>
       * 盤口資訊
       * </pre>
       *
       * <code>repeated .socketProtos.IndexOdds.Odds odds = 2;</code>
       */
      public Builder addOdds(
          int index, Odds.Builder builderForValue) {
        copyOnWrite();
        instance.addOdds(index, builderForValue);
        return this;
      }
      /**
       * <pre>
       * 盤口資訊
       * </pre>
       *
       * <code>repeated .socketProtos.IndexOdds.Odds odds = 2;</code>
       */
      public Builder addAllOdds(
          Iterable<? extends Odds> values) {
        copyOnWrite();
        instance.addAllOdds(values);
        return this;
      }
      /**
       * <pre>
       * 盤口資訊
       * </pre>
       *
       * <code>repeated .socketProtos.IndexOdds.Odds odds = 2;</code>
       */
      public Builder clearOdds() {
        copyOnWrite();
        instance.clearOdds();
        return this;
      }
      /**
       * <pre>
       * 盤口資訊
       * </pre>
       *
       * <code>repeated .socketProtos.IndexOdds.Odds odds = 2;</code>
       */
      public Builder removeOdds(int index) {
        copyOnWrite();
        instance.removeOdds(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:socketProtos.IndexOdds.IndexInfo)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new IndexInfo();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "matchId_",
              "odds_",
              Odds.class,
            };
            String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0001\u0000\u0001\u0004\u0002\u001b" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<IndexInfo> parser = PARSER;
          if (parser == null) {
            synchronized (IndexInfo.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:socketProtos.IndexOdds.IndexInfo)
    private static final IndexInfo DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new IndexInfo();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        IndexInfo.class, DEFAULT_INSTANCE);
    }
    public static IndexInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<IndexInfo> PARSER;

    public static com.google.protobuf.Parser<IndexInfo> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface OddsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:socketProtos.IndexOdds.Odds)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     * 盤口種類 asia亞盤 eu歐盤 bs大小球
     * </pre>
     *
     * <code>string oddType = 1;</code>
     */
    String getOddType();
    /**
     * <pre>
     * 盤口種類 asia亞盤 eu歐盤 bs大小球
     * </pre>
     *
     * <code>string oddType = 1;</code>
     */
    com.google.protobuf.ByteString
        getOddTypeBytes();

    /**
     * <pre>
     * 是否開賽
     * </pre>
     *
     * <code>bool status = 2;</code>
     */
    boolean getStatus();

    /**
     * <pre>
     * 主勝
     * </pre>
     *
     * <code>string home = 3;</code>
     */
    String getHome();
    /**
     * <pre>
     * 主勝
     * </pre>
     *
     * <code>string home = 3;</code>
     */
    com.google.protobuf.ByteString
        getHomeBytes();

    /**
     * <pre>
     * 和、盤口
     * </pre>
     *
     * <code>string handicap = 4;</code>
     */
    String getHandicap();
    /**
     * <pre>
     * 和、盤口
     * </pre>
     *
     * <code>string handicap = 4;</code>
     */
    com.google.protobuf.ByteString
        getHandicapBytes();

    /**
     * <pre>
     * 客勝
     * </pre>
     *
     * <code>string away = 5;</code>
     */
    String getAway();
    /**
     * <pre>
     * 客勝
     * </pre>
     *
     * <code>string away = 5;</code>
     */
    com.google.protobuf.ByteString
        getAwayBytes();

    /**
     * <pre>
     * 變盤時間
     * </pre>
     *
     * <code>int32 timestamp = 6;</code>
     */
    int getTimestamp();

    /**
     * <pre>
     * 是否封盤
     * </pre>
     *
     * <code>bool closed = 7;</code>
     */
    boolean getClosed();
  }
  /**
   * Protobuf type {@code socketProtos.IndexOdds.Odds}
   */
  public  static final class Odds extends
      com.google.protobuf.GeneratedMessageLite<
          Odds, Odds.Builder> implements
      // @@protoc_insertion_point(message_implements:socketProtos.IndexOdds.Odds)
      OddsOrBuilder {
    private Odds() {
      oddType_ = "";
      home_ = "";
      handicap_ = "";
      away_ = "";
    }
    public static final int ODDTYPE_FIELD_NUMBER = 1;
    private String oddType_;
    /**
     * <pre>
     * 盤口種類 asia亞盤 eu歐盤 bs大小球
     * </pre>
     *
     * <code>string oddType = 1;</code>
     */
    @Override
    public String getOddType() {
      return oddType_;
    }
    /**
     * <pre>
     * 盤口種類 asia亞盤 eu歐盤 bs大小球
     * </pre>
     *
     * <code>string oddType = 1;</code>
     */
    @Override
    public com.google.protobuf.ByteString
        getOddTypeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(oddType_);
    }
    /**
     * <pre>
     * 盤口種類 asia亞盤 eu歐盤 bs大小球
     * </pre>
     *
     * <code>string oddType = 1;</code>
     */
    private void setOddType(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      oddType_ = value;
    }
    /**
     * <pre>
     * 盤口種類 asia亞盤 eu歐盤 bs大小球
     * </pre>
     *
     * <code>string oddType = 1;</code>
     */
    private void clearOddType() {
      
      oddType_ = getDefaultInstance().getOddType();
    }
    /**
     * <pre>
     * 盤口種類 asia亞盤 eu歐盤 bs大小球
     * </pre>
     *
     * <code>string oddType = 1;</code>
     */
    private void setOddTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      oddType_ = value.toStringUtf8();
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private boolean status_;
    /**
     * <pre>
     * 是否開賽
     * </pre>
     *
     * <code>bool status = 2;</code>
     */
    @Override
    public boolean getStatus() {
      return status_;
    }
    /**
     * <pre>
     * 是否開賽
     * </pre>
     *
     * <code>bool status = 2;</code>
     */
    private void setStatus(boolean value) {
      
      status_ = value;
    }
    /**
     * <pre>
     * 是否開賽
     * </pre>
     *
     * <code>bool status = 2;</code>
     */
    private void clearStatus() {
      
      status_ = false;
    }

    public static final int HOME_FIELD_NUMBER = 3;
    private String home_;
    /**
     * <pre>
     * 主勝
     * </pre>
     *
     * <code>string home = 3;</code>
     */
    @Override
    public String getHome() {
      return home_;
    }
    /**
     * <pre>
     * 主勝
     * </pre>
     *
     * <code>string home = 3;</code>
     */
    @Override
    public com.google.protobuf.ByteString
        getHomeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(home_);
    }
    /**
     * <pre>
     * 主勝
     * </pre>
     *
     * <code>string home = 3;</code>
     */
    private void setHome(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      home_ = value;
    }
    /**
     * <pre>
     * 主勝
     * </pre>
     *
     * <code>string home = 3;</code>
     */
    private void clearHome() {
      
      home_ = getDefaultInstance().getHome();
    }
    /**
     * <pre>
     * 主勝
     * </pre>
     *
     * <code>string home = 3;</code>
     */
    private void setHomeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      home_ = value.toStringUtf8();
    }

    public static final int HANDICAP_FIELD_NUMBER = 4;
    private String handicap_;
    /**
     * <pre>
     * 和、盤口
     * </pre>
     *
     * <code>string handicap = 4;</code>
     */
    @Override
    public String getHandicap() {
      return handicap_;
    }
    /**
     * <pre>
     * 和、盤口
     * </pre>
     *
     * <code>string handicap = 4;</code>
     */
    @Override
    public com.google.protobuf.ByteString
        getHandicapBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(handicap_);
    }
    /**
     * <pre>
     * 和、盤口
     * </pre>
     *
     * <code>string handicap = 4;</code>
     */
    private void setHandicap(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      handicap_ = value;
    }
    /**
     * <pre>
     * 和、盤口
     * </pre>
     *
     * <code>string handicap = 4;</code>
     */
    private void clearHandicap() {
      
      handicap_ = getDefaultInstance().getHandicap();
    }
    /**
     * <pre>
     * 和、盤口
     * </pre>
     *
     * <code>string handicap = 4;</code>
     */
    private void setHandicapBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      handicap_ = value.toStringUtf8();
    }

    public static final int AWAY_FIELD_NUMBER = 5;
    private String away_;
    /**
     * <pre>
     * 客勝
     * </pre>
     *
     * <code>string away = 5;</code>
     */
    @Override
    public String getAway() {
      return away_;
    }
    /**
     * <pre>
     * 客勝
     * </pre>
     *
     * <code>string away = 5;</code>
     */
    @Override
    public com.google.protobuf.ByteString
        getAwayBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(away_);
    }
    /**
     * <pre>
     * 客勝
     * </pre>
     *
     * <code>string away = 5;</code>
     */
    private void setAway(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      away_ = value;
    }
    /**
     * <pre>
     * 客勝
     * </pre>
     *
     * <code>string away = 5;</code>
     */
    private void clearAway() {
      
      away_ = getDefaultInstance().getAway();
    }
    /**
     * <pre>
     * 客勝
     * </pre>
     *
     * <code>string away = 5;</code>
     */
    private void setAwayBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      away_ = value.toStringUtf8();
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 6;
    private int timestamp_;
    /**
     * <pre>
     * 變盤時間
     * </pre>
     *
     * <code>int32 timestamp = 6;</code>
     */
    @Override
    public int getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * 變盤時間
     * </pre>
     *
     * <code>int32 timestamp = 6;</code>
     */
    private void setTimestamp(int value) {
      
      timestamp_ = value;
    }
    /**
     * <pre>
     * 變盤時間
     * </pre>
     *
     * <code>int32 timestamp = 6;</code>
     */
    private void clearTimestamp() {
      
      timestamp_ = 0;
    }

    public static final int CLOSED_FIELD_NUMBER = 7;
    private boolean closed_;
    /**
     * <pre>
     * 是否封盤
     * </pre>
     *
     * <code>bool closed = 7;</code>
     */
    @Override
    public boolean getClosed() {
      return closed_;
    }
    /**
     * <pre>
     * 是否封盤
     * </pre>
     *
     * <code>bool closed = 7;</code>
     */
    private void setClosed(boolean value) {
      
      closed_ = value;
    }
    /**
     * <pre>
     * 是否封盤
     * </pre>
     *
     * <code>bool closed = 7;</code>
     */
    private void clearClosed() {
      
      closed_ = false;
    }

    public static Odds parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Odds parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Odds parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Odds parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Odds parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Odds parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Odds parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Odds parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Odds parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Odds parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Odds parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Odds parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Odds prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code socketProtos.IndexOdds.Odds}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Odds, Builder> implements
        // @@protoc_insertion_point(builder_implements:socketProtos.IndexOdds.Odds)
        OddsOrBuilder {
      // Construct using com.example.mvvm_navigation.protobuf.SocketIndexOdds.Odds.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       * 盤口種類 asia亞盤 eu歐盤 bs大小球
       * </pre>
       *
       * <code>string oddType = 1;</code>
       */
      @Override
      public String getOddType() {
        return instance.getOddType();
      }
      /**
       * <pre>
       * 盤口種類 asia亞盤 eu歐盤 bs大小球
       * </pre>
       *
       * <code>string oddType = 1;</code>
       */
      @Override
      public com.google.protobuf.ByteString
          getOddTypeBytes() {
        return instance.getOddTypeBytes();
      }
      /**
       * <pre>
       * 盤口種類 asia亞盤 eu歐盤 bs大小球
       * </pre>
       *
       * <code>string oddType = 1;</code>
       */
      public Builder setOddType(
          String value) {
        copyOnWrite();
        instance.setOddType(value);
        return this;
      }
      /**
       * <pre>
       * 盤口種類 asia亞盤 eu歐盤 bs大小球
       * </pre>
       *
       * <code>string oddType = 1;</code>
       */
      public Builder clearOddType() {
        copyOnWrite();
        instance.clearOddType();
        return this;
      }
      /**
       * <pre>
       * 盤口種類 asia亞盤 eu歐盤 bs大小球
       * </pre>
       *
       * <code>string oddType = 1;</code>
       */
      public Builder setOddTypeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setOddTypeBytes(value);
        return this;
      }

      /**
       * <pre>
       * 是否開賽
       * </pre>
       *
       * <code>bool status = 2;</code>
       */
      @Override
      public boolean getStatus() {
        return instance.getStatus();
      }
      /**
       * <pre>
       * 是否開賽
       * </pre>
       *
       * <code>bool status = 2;</code>
       */
      public Builder setStatus(boolean value) {
        copyOnWrite();
        instance.setStatus(value);
        return this;
      }
      /**
       * <pre>
       * 是否開賽
       * </pre>
       *
       * <code>bool status = 2;</code>
       */
      public Builder clearStatus() {
        copyOnWrite();
        instance.clearStatus();
        return this;
      }

      /**
       * <pre>
       * 主勝
       * </pre>
       *
       * <code>string home = 3;</code>
       */
      @Override
      public String getHome() {
        return instance.getHome();
      }
      /**
       * <pre>
       * 主勝
       * </pre>
       *
       * <code>string home = 3;</code>
       */
      @Override
      public com.google.protobuf.ByteString
          getHomeBytes() {
        return instance.getHomeBytes();
      }
      /**
       * <pre>
       * 主勝
       * </pre>
       *
       * <code>string home = 3;</code>
       */
      public Builder setHome(
          String value) {
        copyOnWrite();
        instance.setHome(value);
        return this;
      }
      /**
       * <pre>
       * 主勝
       * </pre>
       *
       * <code>string home = 3;</code>
       */
      public Builder clearHome() {
        copyOnWrite();
        instance.clearHome();
        return this;
      }
      /**
       * <pre>
       * 主勝
       * </pre>
       *
       * <code>string home = 3;</code>
       */
      public Builder setHomeBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setHomeBytes(value);
        return this;
      }

      /**
       * <pre>
       * 和、盤口
       * </pre>
       *
       * <code>string handicap = 4;</code>
       */
      @Override
      public String getHandicap() {
        return instance.getHandicap();
      }
      /**
       * <pre>
       * 和、盤口
       * </pre>
       *
       * <code>string handicap = 4;</code>
       */
      @Override
      public com.google.protobuf.ByteString
          getHandicapBytes() {
        return instance.getHandicapBytes();
      }
      /**
       * <pre>
       * 和、盤口
       * </pre>
       *
       * <code>string handicap = 4;</code>
       */
      public Builder setHandicap(
          String value) {
        copyOnWrite();
        instance.setHandicap(value);
        return this;
      }
      /**
       * <pre>
       * 和、盤口
       * </pre>
       *
       * <code>string handicap = 4;</code>
       */
      public Builder clearHandicap() {
        copyOnWrite();
        instance.clearHandicap();
        return this;
      }
      /**
       * <pre>
       * 和、盤口
       * </pre>
       *
       * <code>string handicap = 4;</code>
       */
      public Builder setHandicapBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setHandicapBytes(value);
        return this;
      }

      /**
       * <pre>
       * 客勝
       * </pre>
       *
       * <code>string away = 5;</code>
       */
      @Override
      public String getAway() {
        return instance.getAway();
      }
      /**
       * <pre>
       * 客勝
       * </pre>
       *
       * <code>string away = 5;</code>
       */
      @Override
      public com.google.protobuf.ByteString
          getAwayBytes() {
        return instance.getAwayBytes();
      }
      /**
       * <pre>
       * 客勝
       * </pre>
       *
       * <code>string away = 5;</code>
       */
      public Builder setAway(
          String value) {
        copyOnWrite();
        instance.setAway(value);
        return this;
      }
      /**
       * <pre>
       * 客勝
       * </pre>
       *
       * <code>string away = 5;</code>
       */
      public Builder clearAway() {
        copyOnWrite();
        instance.clearAway();
        return this;
      }
      /**
       * <pre>
       * 客勝
       * </pre>
       *
       * <code>string away = 5;</code>
       */
      public Builder setAwayBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAwayBytes(value);
        return this;
      }

      /**
       * <pre>
       * 變盤時間
       * </pre>
       *
       * <code>int32 timestamp = 6;</code>
       */
      @Override
      public int getTimestamp() {
        return instance.getTimestamp();
      }
      /**
       * <pre>
       * 變盤時間
       * </pre>
       *
       * <code>int32 timestamp = 6;</code>
       */
      public Builder setTimestamp(int value) {
        copyOnWrite();
        instance.setTimestamp(value);
        return this;
      }
      /**
       * <pre>
       * 變盤時間
       * </pre>
       *
       * <code>int32 timestamp = 6;</code>
       */
      public Builder clearTimestamp() {
        copyOnWrite();
        instance.clearTimestamp();
        return this;
      }

      /**
       * <pre>
       * 是否封盤
       * </pre>
       *
       * <code>bool closed = 7;</code>
       */
      @Override
      public boolean getClosed() {
        return instance.getClosed();
      }
      /**
       * <pre>
       * 是否封盤
       * </pre>
       *
       * <code>bool closed = 7;</code>
       */
      public Builder setClosed(boolean value) {
        copyOnWrite();
        instance.setClosed(value);
        return this;
      }
      /**
       * <pre>
       * 是否封盤
       * </pre>
       *
       * <code>bool closed = 7;</code>
       */
      public Builder clearClosed() {
        copyOnWrite();
        instance.clearClosed();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:socketProtos.IndexOdds.Odds)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Odds();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "oddType_",
              "status_",
              "home_",
              "handicap_",
              "away_",
              "timestamp_",
              "closed_",
            };
            String info =
                "\u0000\u0007\u0000\u0000\u0001\u0007\u0007\u0000\u0000\u0000\u0001\u0208\u0002\u0007" +
                "\u0003\u0208\u0004\u0208\u0005\u0208\u0006\u0004\u0007\u0007";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Odds> parser = PARSER;
          if (parser == null) {
            synchronized (Odds.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:socketProtos.IndexOdds.Odds)
    private static final Odds DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new Odds();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Odds.class, DEFAULT_INSTANCE);
    }
    public static Odds getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Odds> PARSER;

    public static com.google.protobuf.Parser<Odds> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
