// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Socket.proto

package com.example.mvvm_navigation.protobuf;

public final class Socket {
  private Socket() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code socketProtos.command.Command}
   */
  public enum Command
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <pre>
     *系統訊息請忽略
     * </pre>
     *
     * <code>system = 0;</code>
     */
    system(0),
    /**
     * <pre>
     *登入失敗 or 沒有權限
     * </pre>
     *
     * <code>loginFailed = 4001;</code>
     */
    loginFailed(4001),
    /**
     * <pre>
     *重複登入
     * </pre>
     *
     * <code>repeatLogin = 4002;</code>
     */
    repeatLogin(4002),
    /**
     * <pre>
     *參數錯誤
     * </pre>
     *
     * <code>parameterError = 4444;</code>
     */
    parameterError(4444),
    /**
     * <pre>
     *TG賽事資訊變動
     * </pre>
     *
     * <code>tgMatchUpdate = 2001;</code>
     */
    tgMatchUpdate(2001),
    /**
     * <pre>
     *賽事變動通知
     * </pre>
     *
     * <code>matchUpdate = 3001;</code>
     */
    matchUpdate(3001),
    /**
     * <pre>
     *進球通知
     * </pre>
     *
     * <code>goalNotify = 3002;</code>
     */
    goalNotify(3002),
    /**
     * <pre>
     *新賽事資訊通知
     * </pre>
     *
     * <code>newMatches = 3003;</code>
     */
    newMatches(3003),
    /**
     * <pre>
     *賽事開賽時間變動通知
     * </pre>
     *
     * <code>openDateChange = 3004;</code>
     */
    openDateChange(3004),
    /**
     * <pre>
     *賽事刪除通知
     * </pre>
     *
     * <code>deleteMatches = 3005;</code>
     */
    deleteMatches(3005),
    /**
     * <pre>
     * matchDetail = 3006; //賽事詳情通知
     * matchIndex = 3007; //賽事指數通知
     * </pre>
     *
     * <code>indexUpdate = 3008;</code>
     */
    indexUpdate(3008),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *系統訊息請忽略
     * </pre>
     *
     * <code>system = 0;</code>
     */
    public static final int system_VALUE = 0;
    /**
     * <pre>
     *登入失敗 or 沒有權限
     * </pre>
     *
     * <code>loginFailed = 4001;</code>
     */
    public static final int loginFailed_VALUE = 4001;
    /**
     * <pre>
     *重複登入
     * </pre>
     *
     * <code>repeatLogin = 4002;</code>
     */
    public static final int repeatLogin_VALUE = 4002;
    /**
     * <pre>
     *參數錯誤
     * </pre>
     *
     * <code>parameterError = 4444;</code>
     */
    public static final int parameterError_VALUE = 4444;
    /**
     * <pre>
     *TG賽事資訊變動
     * </pre>
     *
     * <code>tgMatchUpdate = 2001;</code>
     */
    public static final int tgMatchUpdate_VALUE = 2001;
    /**
     * <pre>
     *賽事變動通知
     * </pre>
     *
     * <code>matchUpdate = 3001;</code>
     */
    public static final int matchUpdate_VALUE = 3001;
    /**
     * <pre>
     *進球通知
     * </pre>
     *
     * <code>goalNotify = 3002;</code>
     */
    public static final int goalNotify_VALUE = 3002;
    /**
     * <pre>
     *新賽事資訊通知
     * </pre>
     *
     * <code>newMatches = 3003;</code>
     */
    public static final int newMatches_VALUE = 3003;
    /**
     * <pre>
     *賽事開賽時間變動通知
     * </pre>
     *
     * <code>openDateChange = 3004;</code>
     */
    public static final int openDateChange_VALUE = 3004;
    /**
     * <pre>
     *賽事刪除通知
     * </pre>
     *
     * <code>deleteMatches = 3005;</code>
     */
    public static final int deleteMatches_VALUE = 3005;
    /**
     * <pre>
     * matchDetail = 3006; //賽事詳情通知
     * matchIndex = 3007; //賽事指數通知
     * </pre>
     *
     * <code>indexUpdate = 3008;</code>
     */
    public static final int indexUpdate_VALUE = 3008;


    @Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Command valueOf(int value) {
      return forNumber(value);
    }

    public static Command forNumber(int value) {
      switch (value) {
        case 0: return system;
        case 4001: return loginFailed;
        case 4002: return repeatLogin;
        case 4444: return parameterError;
        case 2001: return tgMatchUpdate;
        case 3001: return matchUpdate;
        case 3002: return goalNotify;
        case 3003: return newMatches;
        case 3004: return openDateChange;
        case 3005: return deleteMatches;
        case 3008: return indexUpdate;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Command>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Command> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Command>() {
            @Override
            public Command findValueByNumber(int number) {
              return Command.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return CommandVerifier.INSTANCE;
    }

    private static final class CommandVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new CommandVerifier();
            @Override
            public boolean isInRange(int number) {
              return Command.forNumber(number) != null;
            }
          };

    private final int value;

    private Command(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:socketProtos.command.Command)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
